#
# production settings
# 
# (version: 86, saved: 2020-03-22 00:46:49)
#
---
production:
  settings:
    id: illusionaryquest
    caption: illusionary Quest
    menuvisibile: true
    enabled: true
    storesdata: true
    strings-idspace: 9999
    strings-idstart: 0
    version: 86
